# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20200702_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_fin',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_ini',
            field=models.CharField(max_length=8),
        ),
    ]
